name = "integrations"

[defaults]
builder = "docker:node"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[builders."docker:node"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "mixed-builders"
instances = { min = 2, max = 2, default = 2 }

[testcases.params]
  expected_implementation = { type = "string", desc = "expected implementation" }
