name = "additional_envs"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[runners."local:docker"]
enabled = true
additional_envs = { MY_FIRST_CUSTOM_ENV_VARIABLE = "Hello, AdditionalEnvs!" }

[[testcases]]
name = "additional_envs"
instances = { min = 1, max = 1, default = 1 }
