name = "additional_envs"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:docker".additional_envs]
TESTGROUND_HELLO_MESSAGE = "Hello, AdditionalEnvs!"

[[testcases]]
name = "additional_envs"
instances = { min = 1, max = 1, default = 1 }
